<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ToolsSeeder extends Seeder
{
    public function run(): void
    {
        $tools = [
            // ── Sleep Tools ──────────────────────────────────────────────────────
            [
                'name'             => 'Sleep Calculator',
                'slug'             => 'sleep-calculator',
                'category'         => 'sleep',
                'icon'             => '😴',
                'description'      => 'Find the best bedtime or wake-up time based on 90-minute sleep cycles.',
                'meta_title'       => 'Sleep Calculator — Best Bedtime & Wake-Up Time | MindSnap',
                'meta_description' => 'Enter your wake-up time and get the ideal bedtime based on 90-minute sleep cycles. Free, instant, no signup.',
                'monthly_searches'  => 2200000,
                'sort_order'       => 10,
                'is_active'        => true,
            ],
            [
                'name'             => 'Wake-Up Calculator',
                'slug'             => 'wake-up-calculator',
                'category'         => 'sleep',
                'icon'             => '⏰',
                'description'      => 'Calculate the best times to wake up feeling refreshed and alert.',
                'meta_title'       => 'Wake-Up Calculator — Best Times to Wake Up | MindSnap',
                'meta_description' => 'Enter your bedtime and find the optimal wake-up times to avoid sleep inertia. Based on 90-minute sleep cycles.',
                'monthly_searches'  => 480000,
                'sort_order'       => 20,
                'is_active'        => true,
            ],
            [
                'name'             => 'Nap Calculator',
                'slug'             => 'nap-calculator',
                'category'         => 'sleep',
                'icon'             => '💤',
                'description'      => 'Find the perfect nap length — power nap, full cycle, or recovery nap.',
                'meta_title'       => 'Nap Calculator — Ideal Nap Duration & Wake-Up Time | MindSnap',
                'meta_description' => 'Calculate the best nap duration to avoid grogginess. Power nap (20 min) to full sleep cycle options.',
                'monthly_searches'  => 110000,
                'sort_order'       => 30,
                'is_active'        => true,
            ],
            [
                'name'             => 'Baby Sleep Calculator',
                'slug'             => 'baby-sleep-calculator',
                'category'         => 'sleep',
                'icon'             => '👶',
                'description'      => 'Age-appropriate sleep schedules and total hours for babies and toddlers.',
                'meta_title'       => 'Baby Sleep Calculator — Schedules by Age | MindSnap',
                'meta_description' => 'How much sleep does your baby need? Get age-appropriate sleep schedules for newborns through toddlers.',
                'monthly_searches'  => 165000,
                'sort_order'       => 40,
                'is_active'        => true,
            ],
            [
                'name'             => 'Sleep Debt Calculator',
                'slug'             => 'sleep-debt-calculator',
                'category'         => 'sleep',
                'icon'             => '📉',
                'description'      => 'Track how much sleep you owe your body and how long recovery takes.',
                'meta_title'       => 'Sleep Debt Calculator — How Much Sleep Do You Owe? | MindSnap',
                'meta_description' => 'Calculate your accumulated sleep debt and get a personalised recovery plan. Based on sleep science research.',
                'monthly_searches'  => 74000,
                'sort_order'       => 50,
                'is_active'        => true,
            ],
            [
                'name'             => 'Caffeine & Sleep Calculator',
                'slug'             => 'caffeine-sleep-calculator',
                'category'         => 'sleep',
                'icon'             => '☕',
                'description'      => 'Find the last safe time to drink coffee so it does not disrupt your sleep.',
                'meta_title'       => 'Caffeine Sleep Calculator — Last Safe Coffee Time | MindSnap',
                'meta_description' => 'Enter your bedtime and find the latest time you can drink caffeine without wrecking your sleep.',
                'monthly_searches'  => 40000,
                'sort_order'       => 60,
                'is_active'        => true,
            ],
            [
                'name'             => 'Jet Lag Calculator',
                'slug'             => 'jet-lag-calculator',
                'category'         => 'sleep',
                'icon'             => '✈️',
                'description'      => 'Beat jet lag with a custom sleep schedule for your destination timezone.',
                'meta_title'       => 'Jet Lag Calculator — Recovery Schedule by Time Zone | MindSnap',
                'meta_description' => 'Plan your sleep before, during, and after a long-haul flight to minimise jet lag symptoms.',
                'monthly_searches'  => 49000,
                'sort_order'       => 70,
                'is_active'        => true,
            ],
            [
                'name'             => 'Sleep Quality Quiz',
                'slug'             => 'sleep-quality-quiz',
                'category'         => 'sleep',
                'icon'             => '📋',
                'description'      => 'Assess your sleep quality with this science-backed questionnaire.',
                'meta_title'       => 'Sleep Quality Quiz — Rate Your Sleep Health | MindSnap',
                'meta_description' => 'Answer 10 questions based on the Pittsburgh Sleep Quality Index and get your personalised sleep score.',
                'monthly_searches'  => 22000,
                'sort_order'       => 80,
                'is_active'        => true,
            ],

            // ── Fitness Tools ────────────────────────────────────────────────────
            [
                'name'             => 'BMI Calculator',
                'slug'             => 'bmi-calculator',
                'category'         => 'fitness',
                'icon'             => '⚖️',
                'description'      => 'Calculate your Body Mass Index and understand what the number means.',
                'meta_title'       => 'BMI Calculator — Body Mass Index for Adults | MindSnap',
                'meta_description' => 'Calculate your BMI instantly in metric or imperial. Get your weight category and healthy range recommendations.',
                'monthly_searches'  => 4400000,
                'sort_order'       => 10,
                'is_active'        => true,
            ],
            [
                'name'             => 'Calorie Calculator',
                'slug'             => 'calorie-calculator',
                'category'         => 'fitness',
                'icon'             => '🔥',
                'description'      => 'Calculate your TDEE — total daily energy expenditure — to hit your goals.',
                'meta_title'       => 'Calorie Calculator — Daily Calorie Needs (TDEE) | MindSnap',
                'meta_description' => 'Find out exactly how many calories you need to maintain, lose, or gain weight based on your age, height, weight, and activity level.',
                'monthly_searches'  => 1830000,
                'sort_order'       => 20,
                'is_active'        => true,
            ],
            [
                'name'             => 'Calorie Deficit Calculator',
                'slug'             => 'calorie-deficit-calculator',
                'category'         => 'fitness',
                'icon'             => '📊',
                'description'      => 'Find the right calorie deficit to lose weight safely without muscle loss.',
                'meta_title'       => 'Calorie Deficit Calculator — Safe Weight Loss | MindSnap',
                'meta_description' => 'Calculate your ideal calorie deficit for steady, sustainable weight loss. Includes projected timeline to goal weight.',
                'monthly_searches'  => 246000,
                'sort_order'       => 30,
                'is_active'        => true,
            ],
            [
                'name'             => 'Macro Calculator',
                'slug'             => 'macro-calculator',
                'category'         => 'fitness',
                'icon'             => '🥩',
                'description'      => 'Get your ideal protein, carb, and fat targets for any fitness goal.',
                'meta_title'       => 'Macro Calculator — Protein, Carbs & Fat Targets | MindSnap',
                'meta_description' => 'Calculate your macronutrient targets for weight loss, muscle gain, or maintenance. Adjustable for keto, paleo, and standard diets.',
                'monthly_searches'  => 550000,
                'sort_order'       => 40,
                'is_active'        => true,
            ],
            [
                'name'             => 'Protein Calculator',
                'slug'             => 'protein-calculator',
                'category'         => 'fitness',
                'icon'             => '💪',
                'description'      => 'Calculate daily protein intake based on your weight, goals, and activity.',
                'meta_title'       => 'Protein Calculator — Daily Protein Intake by Goal | MindSnap',
                'meta_description' => 'How much protein do you actually need? Get a target tailored to your weight, training intensity, and goal.',
                'monthly_searches'  => 368000,
                'sort_order'       => 50,
                'is_active'        => true,
            ],
            [
                'name'             => 'One Rep Max Calculator',
                'slug'             => 'one-rep-max-calculator',
                'category'         => 'fitness',
                'icon'             => '🏋️',
                'description'      => 'Estimate your 1RM for any lift using multiple proven formulas.',
                'meta_title'       => 'One Rep Max Calculator — Estimate Your 1RM | MindSnap',
                'meta_description' => 'Enter your weight and reps to estimate your one-rep max using Brzycki, Epley, and Lombardi formulas.',
                'monthly_searches'  => 165000,
                'sort_order'       => 60,
                'is_active'        => true,
            ],
            [
                'name'             => 'Body Fat Calculator',
                'slug'             => 'body-fat-calculator',
                'category'         => 'fitness',
                'icon'             => '📐',
                'description'      => 'Estimate body fat percentage using the US Navy measurement method.',
                'meta_title'       => 'Body Fat Calculator — Estimate Your Body Fat % | MindSnap',
                'meta_description' => 'Calculate your body fat percentage using the US Navy method. Includes lean mass and fat mass breakdown.',
                'monthly_searches'  => 246000,
                'sort_order'       => 70,
                'is_active'        => true,
            ],
            [
                'name'             => 'Heart Rate Calculator',
                'slug'             => 'heart-rate-calculator',
                'category'         => 'fitness',
                'icon'             => '❤️',
                'description'      => 'Find your max heart rate and ideal training zones for fat burn and cardio.',
                'meta_title'       => 'Heart Rate Calculator — Training Zones by Age | MindSnap',
                'meta_description' => 'Calculate your maximum heart rate and five training zones. Know exactly which zone to target for fat burn, cardio, and peak performance.',
                'monthly_searches'  => 201000,
                'sort_order'       => 80,
                'is_active'        => true,
            ],
            [
                'name'             => 'Running Pace Calculator',
                'slug'             => 'running-pace-calculator',
                'category'         => 'fitness',
                'icon'             => '🏃',
                'description'      => 'Convert between pace, speed, and finish time for any race distance.',
                'meta_title'       => 'Running Pace Calculator — Pace, Speed & Finish Time | MindSnap',
                'meta_description' => 'Calculate your running pace, estimated finish time, or required speed for 5K, 10K, half marathon, and marathon.',
                'monthly_searches'  => 135000,
                'sort_order'       => 90,
                'is_active'        => true,
            ],
            [
                'name'             => 'Ideal Weight Calculator',
                'slug'             => 'ideal-weight-calculator',
                'category'         => 'fitness',
                'icon'             => '🎯',
                'description'      => 'Find your healthy weight range based on height using four medical formulas.',
                'meta_title'       => 'Ideal Weight Calculator — Healthy Weight by Height | MindSnap',
                'meta_description' => 'Calculate your ideal body weight range using Robinson, Miller, Hamwi, and Devine formulas. Metric and imperial.',
                'monthly_searches'  => 301000,
                'sort_order'       => 100,
                'is_active'        => true,
            ],
            [
                'name'             => 'Workout Volume Calculator',
                'slug'             => 'workout-volume-calculator',
                'category'         => 'fitness',
                'icon'             => '📋',
                'description'      => 'Track total training volume (sets × reps × weight) for progressive overload.',
                'meta_title'       => 'Workout Volume Calculator — Track Training Load | MindSnap',
                'meta_description' => 'Calculate your total workout volume per session or week. Track progressive overload for strength and hypertrophy.',
                'monthly_searches'  => 18000,
                'sort_order'       => 110,
                'is_active'        => true,
            ],

            // ── Nutrition Tools ──────────────────────────────────────────────────
            [
                'name'             => 'Water Intake Calculator',
                'slug'             => 'water-intake-calculator',
                'category'         => 'nutrition',
                'icon'             => '💧',
                'description'      => 'Calculate daily water intake needs based on weight, climate, and activity.',
                'meta_title'       => 'Water Intake Calculator — Daily Hydration Goal | MindSnap',
                'meta_description' => 'Find out exactly how much water you should drink per day based on your weight, activity level, and climate.',
                'monthly_searches'  => 368000,
                'sort_order'       => 10,
                'is_active'        => true,
            ],
            [
                'name'             => 'Intermittent Fasting Calculator',
                'slug'             => 'intermittent-fasting-calculator',
                'category'         => 'nutrition',
                'icon'             => '🕐',
                'description'      => 'Plan your eating and fasting windows for 16:8, 5:2, and other IF protocols.',
                'meta_title'       => 'Intermittent Fasting Calculator — Eating Windows | MindSnap',
                'meta_description' => 'Set your fasting window, eating window start time, and get your personalised IF schedule for 16:8, 18:6, or 5:2.',
                'monthly_searches'  => 201000,
                'sort_order'       => 20,
                'is_active'        => true,
            ],

            // ── Kids Zone ────────────────────────────────────────────────────────
            [
                'name'             => 'Math Puzzles',
                'slug'             => 'kids/math-puzzles',
                'category'         => 'kids',
                'icon'             => '🔢',
                'description'      => 'Fun, age-appropriate maths challenges for children aged 6–12.',
                'meta_title'       => 'Kids Math Puzzles — Fun Brain Teasers | MindSnap',
                'meta_description' => 'Free maths puzzles for kids aged 6–12. Addition, subtraction, multiplication and more — no ads, no signup.',
                'monthly_searches'  => 74000,
                'sort_order'       => 10,
                'is_active'        => true,
            ],
            [
                'name'             => 'Word Games',
                'slug'             => 'kids/word-games',
                'category'         => 'kids',
                'icon'             => '📝',
                'description'      => 'Vocabulary games that make learning words genuinely fun for kids.',
                'meta_title'       => 'Kids Word Games — Free Vocabulary Activities | MindSnap',
                'meta_description' => 'Free word games for kids — spelling challenges, word building, and vocabulary activities. Safe, no ads.',
                'monthly_searches'  => 49000,
                'sort_order'       => 20,
                'is_active'        => true,
            ],
            [
                'name'             => 'Science Quiz for Kids',
                'slug'             => 'kids/science-quiz',
                'category'         => 'kids',
                'icon'             => '🔬',
                'description'      => 'Discover cool science facts with questions designed for curious young minds.',
                'meta_title'       => 'Science Quiz for Kids — Fun Science Questions | MindSnap',
                'meta_description' => 'Free science quiz for kids aged 6–14. Biology, chemistry, physics, and space — 15 questions, instant results.',
                'monthly_searches'  => 33000,
                'sort_order'       => 30,
                'is_active'        => true,
            ],
            [
                'name'             => 'Animal Quiz for Kids',
                'slug'             => 'kids/animal-quiz',
                'category'         => 'kids',
                'icon'             => '🦁',
                'description'      => 'How much do kids know about animals? 15 fun questions from easy to tricky.',
                'meta_title'       => 'Animal Quiz for Kids — 15 Fun Questions | MindSnap',
                'meta_description' => 'Free animal quiz for kids. Mammals, reptiles, ocean creatures — 15 illustrated questions. No signup, no ads.',
                'monthly_searches'  => 27000,
                'sort_order'       => 40,
                'is_active'        => true,
            ],
            [
                'name'             => 'Spelling Quiz for Kids',
                'slug'             => 'kids/spelling-quiz',
                'category'         => 'kids',
                'icon'             => '🔤',
                'description'      => 'Practice spelling with graded word lists for primary school children.',
                'meta_title'       => 'Spelling Quiz for Kids — Practice Word Lists | MindSnap',
                'meta_description' => 'Free spelling quiz for kids. Graded word lists from Year 1 through Year 6. Practice anytime, no signup.',
                'monthly_searches'  => 22000,
                'sort_order'       => 50,
                'is_active'        => true,
            ],

            // ── Life Tools ───────────────────────────────────────────────────────
            [
                'name'             => 'Age Calculator',
                'slug'             => 'age-calculator',
                'category'         => 'life',
                'icon'             => '🎂',
                'description'      => 'Calculate exact age in years, months, weeks, and days from any date.',
                'meta_title'       => 'Age Calculator — Exact Age in Years, Months & Days | MindSnap',
                'meta_description' => 'Enter your date of birth and instantly get your exact age in years, months, weeks, days, and hours.',
                'monthly_searches'  => 4400000,
                'sort_order'       => 10,
                'is_active'        => true,
            ],
            [
                'name'             => 'Days Between Dates',
                'slug'             => 'days-between-dates',
                'category'         => 'life',
                'icon'             => '📆',
                'description'      => 'Count the exact number of days, weeks, and months between two dates.',
                'meta_title'       => 'Days Between Dates Calculator | MindSnap',
                'meta_description' => 'Calculate the exact number of days, weeks, and months between any two dates. Includes business days option.',
                'monthly_searches'  => 550000,
                'sort_order'       => 20,
                'is_active'        => true,
            ],
            [
                'name'             => 'Days Until Calculator',
                'slug'             => 'days-until-calculator',
                'category'         => 'life',
                'icon'             => '⏳',
                'description'      => 'Count down to any future date — holidays, birthdays, events.',
                'meta_title'       => 'Days Until Calculator — Countdown to Any Date | MindSnap',
                'meta_description' => 'How many days until your birthday, Christmas, or any event? Get an instant countdown in days, hours, and minutes.',
                'monthly_searches'  => 135000,
                'sort_order'       => 30,
                'is_active'        => true,
            ],
            [
                'name'             => 'Due Date Calculator',
                'slug'             => 'due-date-calculator',
                'category'         => 'life',
                'icon'             => '🤰',
                'description'      => 'Calculate your pregnancy due date and trimester milestones.',
                'meta_title'       => 'Due Date Calculator — Pregnancy Due Date | MindSnap',
                'meta_description' => 'Enter your last menstrual period date to calculate your estimated due date and pregnancy week-by-week milestones.',
                'monthly_searches'  => 1220000,
                'sort_order'       => 40,
                'is_active'        => true,
            ],
            [
                'name'             => 'Ovulation Calculator',
                'slug'             => 'ovulation-calculator',
                'category'         => 'life',
                'icon'             => '🌸',
                'description'      => 'Estimate your ovulation date and fertile window based on your cycle.',
                'meta_title'       => 'Ovulation Calculator — Fertile Window & Ovulation Date | MindSnap',
                'meta_description' => 'Calculate your most fertile days and estimated ovulation date based on your menstrual cycle length.',
                'monthly_searches'  => 1000000,
                'sort_order'       => 50,
                'is_active'        => true,
            ],
            [
                'name'             => 'Retirement Calculator',
                'slug'             => 'retirement-calculator',
                'category'         => 'life',
                'icon'             => '🏖️',
                'description'      => 'Find out when you can retire and how much you need to save.',
                'meta_title'       => 'Retirement Calculator — When Can You Retire? | MindSnap',
                'meta_description' => 'Enter your age, savings, and monthly contributions to calculate your retirement date and projected nest egg.',
                'monthly_searches'  => 368000,
                'sort_order'       => 60,
                'is_active'        => true,
            ],
            [
                'name'             => 'Life Percentage Calculator',
                'slug'             => 'life-percentage-calculator',
                'category'         => 'life',
                'icon'             => '⌛',
                'description'      => 'See what percentage of your life you have lived — and what is left.',
                'meta_title'       => 'Life Percentage Calculator — How Much Life Have You Lived? | MindSnap',
                'meta_description' => 'Enter your age and life expectancy to see what percentage of your life has passed. A powerful perspective tool.',
                'monthly_searches'  => 22000,
                'sort_order'       => 70,
                'is_active'        => true,
            ],

            // ── Games ────────────────────────────────────────────────────────────
            [
                'name'             => 'Typing Speed Test',
                'slug'             => 'typing-speed-test',
                'category'         => 'games',
                'icon'             => '⌨️',
                'description'      => 'Measure your WPM and accuracy with real passages in 60 seconds.',
                'meta_title'       => 'Typing Speed Test — WPM & Accuracy | MindSnap',
                'meta_description' => 'Test your typing speed and accuracy. Get your WPM score with real text passages. 30-second and 60-second modes.',
                'monthly_searches'  => 1500000,
                'sort_order'       => 10,
                'is_active'        => true,
            ],
            [
                'name'             => 'Reaction Time Test',
                'slug'             => 'reaction-time-test',
                'category'         => 'games',
                'icon'             => '⚡',
                'description'      => 'How fast are your reflexes? Measure your reaction time in milliseconds.',
                'meta_title'       => 'Reaction Time Test — Measure Your Reflexes | MindSnap',
                'meta_description' => 'Test your reaction speed in milliseconds. Compare your score to average human reaction times. 5-round average.',
                'monthly_searches'  => 301000,
                'sort_order'       => 20,
                'is_active'        => true,
            ],
            [
                'name'             => 'Memory Test',
                'slug'             => 'memory-test',
                'category'         => 'games',
                'icon'             => '🧠',
                'description'      => 'Test your short-term memory with a classic number sequence challenge.',
                'meta_title'       => 'Memory Test — Short-Term Memory Challenge | MindSnap',
                'meta_description' => 'How long a number sequence can you remember? Free memory test based on digit span — a classic cognitive measure.',
                'monthly_searches'  => 165000,
                'sort_order'       => 30,
                'is_active'        => true,
            ],
            [
                'name'             => 'Word Scramble',
                'slug'             => 'word-scramble',
                'category'         => 'games',
                'icon'             => '🔀',
                'description'      => 'Unscramble words against the clock — five difficulty levels.',
                'meta_title'       => 'Word Scramble Game — Unscramble Words | MindSnap',
                'meta_description' => 'Unscramble words as fast as you can in this free word puzzle game. Five difficulty levels from easy to expert.',
                'monthly_searches'  => 110000,
                'sort_order'       => 40,
                'is_active'        => true,
            ],
            [
                'name'             => 'Color Blind Test',
                'slug'             => 'color-blind-test',
                'category'         => 'games',
                'icon'             => '🎨',
                'description'      => 'A series of Ishihara-style plates to screen for colour vision deficiency.',
                'meta_title'       => 'Color Blind Test — Free Online Colour Vision Test | MindSnap',
                'meta_description' => 'Take a free Ishihara-style color blind test. Screens for red-green and blue-yellow colour vision deficiency. 15 plates.',
                'monthly_searches'  => 550000,
                'sort_order'       => 50,
                'is_active'        => true,
            ],
        ];

        foreach ($tools as &$tool) {
            $tool['created_at']   = now();
            $tool['updated_at']   = now();
            $tool['published_at'] = now();
        }

        DB::table('tools')->upsert(
            $tools,
            ['slug'],
            ['name', 'category', 'icon', 'description', 'meta_title', 'meta_description', 'monthly_searches', 'sort_order', 'is_active', 'updated_at']
        );
    }
}
